language: node_js
node_js:
  - 'node'
before_install:
  - cd extension
env:
  - EXTENSION_ID=lpnakhpaodhdkleejaehlapdhbgjbddp
deploy:
  provider: script
  skip_cleanup: true
  script: cd extension && npm run release
  on:
    branch: master
    tags: true
